"""`tidd docs-sync` サブコマンド（Issue #2578）.

全 tidd コマンドの argparse メタデータ（コマンド名・description/help・引数一覧）から
`docs/reference/tidd-cli-reference.md` を決定論的に生成する。

生成のたびに同一入力 → 同一出力となるよう、タイムスタンプ等の揮発情報を含まない。

pre-flight の drift 検知チェックと連携して使用する。コマンド追加・変更後は
`tidd docs-sync` を実行して生成物をコミットすること。
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from tidd_tools.shared.cli import add_common_flags
from tidd_tools.shared.errors import SubprocessTimeoutError
from tidd_tools.shared.subprocess_runner import run as run_subprocess
from tidd_tools.shared.subprocess_timeouts import QUICK_TIMEOUT_SEC

# リポジトリルートからの相対パス（docs-sync のデフォルト出力先）
_DEFAULT_OUTPUT_RELPATH = "docs/reference/tidd-cli-reference.md"


def register(subparsers: argparse._SubParsersAction[argparse.ArgumentParser]) -> None:
    parser = subparsers.add_parser(
        "docs-sync",
        help="全コマンドの argparse メタデータから tidd-cli-reference.md を生成する（Issue #2578）",
        description=__doc__,
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=None,
        help=(f"出力先ファイルパス（省略時: リポジトリルートの {_DEFAULT_OUTPUT_RELPATH}）"),
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="生成結果と commit 済みファイルの差分を検知して exit 1 を返す（drift チェック）",
    )
    add_common_flags(parser)
    parser.set_defaults(func=run_cli)


def _resolve_repo_root() -> Path:
    """リポジトリルートを解決する."""
    try:
        proc = run_subprocess(
            ["git", "rev-parse", "--show-toplevel"],
            timeout=QUICK_TIMEOUT_SEC,
        )
        if proc.returncode == 0:
            return Path(proc.stdout.strip())
    except (FileNotFoundError, SubprocessTimeoutError):
        pass
    return Path.cwd()


def _get_subparsers_action(
    parser: argparse.ArgumentParser,
) -> argparse._SubParsersAction[argparse.ArgumentParser] | None:
    """パーサーから subparsers action を取得する."""
    for action in parser._actions:
        if isinstance(action, argparse._SubParsersAction):
            return action
    return None


# 共通フラグ（-h/--help / -v/--verbose / --dry-run / --json）の dest 一覧
_COMMON_DESTS: frozenset[str] = frozenset({"help", "verbose", "dry_run", "json_output"})


def _format_argument(action: argparse.Action) -> str | None:
    """引数の markdown 表現を生成する.

    共通フラグ（-h/--help / -v/--verbose / --dry-run / --json）は除外する。
    """
    dest = getattr(action, "dest", None)
    if dest in _COMMON_DESTS:
        return None

    option_strings: list[str] = getattr(action, "option_strings", [])
    help_text: str = action.help or ""

    # metavar 取得（positional 引数は dest を大文字で使う慣習）
    metavar: str | None = getattr(action, "metavar", None)
    if metavar is None:
        metavar = (dest or "ARG").upper() if not option_strings else None

    # 引数表示文字列
    if option_strings:
        opts_str = ", ".join(option_strings)
        if metavar:
            arg_repr = f"`{opts_str} {metavar}`"
        elif isinstance(action, (argparse._StoreTrueAction, argparse._StoreFalseAction, argparse._CountAction)):
            arg_repr = f"`{opts_str}`"
        else:
            arg_repr = f"`{opts_str} <value>`"
    else:
        arg_repr = f"`{metavar}`"

    # 必須/任意
    is_required = getattr(action, "required", False)
    if not option_strings:
        if isinstance(action, argparse._SubParsersAction):
            # Issue #3569: add_subparsers() の nargs は常に PARSER 固定のため、
            # 下記の nargs ベースの判定（positional 全般向け）を適用すると
            # `required=False` で登録したサブコマンド（例: `tidd config`）が
            # 誤って「（必須）」と表示される。action.required の明示値をそのまま使う。
            is_required = bool(getattr(action, "required", False))
        else:
            # positional: nargs="?"（0 or 1）/ "*"（0 or more）は省略可能なので任意扱い。
            # それ以外（デフォルトの nargs=None・"+" 等）は常に必須。
            nargs = getattr(action, "nargs", None)
            is_required = nargs not in (argparse.OPTIONAL, argparse.ZERO_OR_MORE)
    required_tag = "（必須）" if is_required else "（任意）"

    line = f"- {arg_repr}: {help_text}{required_tag}"
    return line


def generate_reference() -> str:
    """argparse メタデータから tidd-cli-reference.md の内容を生成する.

    決定論的（タイムスタンプ等の揮発情報なし）。コマンドは名前順で並ぶ。
    """
    # __main__._build_parser() を呼び出してパーサーを構築する
    from tidd_tools.__main__ import _build_parser

    parser = _build_parser()
    subparsers_action = _get_subparsers_action(parser)
    if subparsers_action is None:
        return "# tidd CLI リファレンス\n\n（コマンドが登録されていません）\n"

    lines: list[str] = [
        "# tidd CLI リファレンス",
        "",
        "このファイルは `tidd docs-sync` により自動生成されます。手動で編集しないでください。",
        "コマンドを追加・変更した後は `tidd docs-sync` を実行して再生成しコミットしてください。",
        "",
        "<!-- generated by tidd docs-sync (Issue #2578) -->",
        "",
    ]

    choices: dict[str, argparse.ArgumentParser] = subparsers_action.choices
    for name in sorted(choices.keys()):
        sp = choices[name]
        # コマンド見出し
        lines.append(f"## `tidd {name}`")
        lines.append("")

        # description（--help 表示の詳細説明）を優先。なければ help を使う
        desc = (sp.description or "").strip()
        if desc:
            # 複数行の場合は最初の段落のみ（詳細は --help で確認）
            first_para = desc.split("\n\n")[0].replace("\n", " ").strip()
            lines.append(first_para)
        else:
            # サブコマンドの prog 経由で help を取得
            # （subparsers_action.choices のキーに対応する help は
            #   subparsers_action._name_parser_map には存在しないため
            #   _choices_actions から取得する）
            cmd_help = ""
            for ca in subparsers_action._choices_actions:
                if ca.dest == name:
                    cmd_help = ca.help or ""
                    break
            if cmd_help:
                lines.append(cmd_help)

        lines.append("")

        # 引数一覧（共通フラグを除く）
        arg_lines: list[str] = []
        for action in sp._actions:
            formatted = _format_argument(action)
            if formatted is not None:
                arg_lines.append(formatted)

        if arg_lines:
            lines.append("**引数:**")
            lines.append("")
            lines.extend(arg_lines)
        else:
            lines.append("（固有引数なし）")

        lines.append("")

    content = "\n".join(lines)
    # help 文字列に Path.home() 展開済みのデフォルト値が混入すると生成物が
    # マシン依存になり、他環境の pre-flight drift 検知が誤爆する（#2578）。
    # ホームディレクトリ絶対パスは ~ 表記に正規化する。
    home = str(Path.home())
    if home not in ("/", ""):
        content = content.replace(home, "~")
    return content


def check_drift(output_path: Path) -> bool:
    """commit 済みファイルと再生成結果の差分を検知する.

    Args:
        output_path: チェック対象のファイルパス

    Returns:
        True: drift あり（再生成結果と異なる）
        False: drift なし（再生成結果と一致）
    """
    if not output_path.is_file():
        return True  # ファイルが存在しない = drift あり

    committed = output_path.read_text(encoding="utf-8")
    generated = generate_reference()
    return committed != generated


def run_cli(args: argparse.Namespace) -> int:
    """docs-sync サブコマンドのエントリポイント."""
    # 出力先の解決
    if args.output is not None:
        output_path = args.output
    else:
        repo_root = _resolve_repo_root()
        output_path = repo_root / _DEFAULT_OUTPUT_RELPATH

    if getattr(args, "check", False):
        # drift チェックモード
        has_drift = check_drift(output_path)
        if has_drift:
            print(
                f"ERROR: docs-sync: {output_path} が最新の CLI 定義と一致しません。\n"
                "       `tidd docs-sync` を実行して再生成し、コミットしてください。",
                file=sys.stderr,
            )
            return 1
        print(f"docs-sync: {output_path} は最新です（drift なし）")
        return 0

    # 生成モード
    content = generate_reference()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8")
    print(f"docs-sync: {output_path} を生成しました（{len(content)} bytes）")
    return 0
